module.exports = {
  apps: [
    {
      name: 'command-processor',
      script: 'index.js',
      cwd: './demos/block3/packages/command-processor',
      env: {
        FORCE_COLOR: 1,
        LOG_LEVEL: 'trace',
        EVENT_STORE_MONGODB_URL_SCHEME: 'mongodb',
        EVENT_STORE_MONGODB_SERVER: '127.0.0.1',
        EVENT_STORE_MONGODB_URL_PATH: '',
        EVENT_STORE_MONGODB_USER: '',
        EVENT_STORE_MONGODB_PWD: '',
        EVENT_STORE_DATABASE: 'events',
        EVENT_STORE_COLLECTION: 'events',
      },
    },
    {
      name: 'readmodel-customers',
      script: 'index.js',
      cwd: './demos/block3/packages/readmodel-customers',
      env: {
        FORCE_COLOR: 1,
        LOG_LEVEL: 'trace',
        EVENT_STORE_MONGODB_URL_SCHEME: 'mongodb',
        EVENT_STORE_MONGODB_SERVER: '127.0.0.1',
        EVENT_STORE_MONGODB_URL_PATH: '',
        EVENT_STORE_MONGODB_USER: '',
        EVENT_STORE_MONGODB_PWD: '',
        STORE_DATABASE: 'readmodel-customers',
        API_PORT: 3003,
        COMMAND_ENDPOINT: 'http://127.0.0.1:3001/api/command',
      },
    },
    {
      name: 'readmodel-orders',
      script: 'index.js',
      cwd: './demos/block3/packages/readmodel-orders',
      env: {
        FORCE_COLOR: 1,
        LOG_LEVEL: 'trace',
        EVENT_STORE_MONGODB_URL_SCHEME: 'mongodb',
        EVENT_STORE_MONGODB_SERVER: '127.0.0.1',
        EVENT_STORE_MONGODB_URL_PATH: '',
        EVENT_STORE_MONGODB_USER: '',
        EVENT_STORE_MONGODB_PWD: '',
        STORE_DATABASE: 'readmodel-orders',
        API_PORT: 3005,
        COMMAND_ENDPOINT: 'http://127.0.0.1:3001/api/command',
      },
    },
    {
      name: 'frontend-react',
      cwd: '.',
      script: 'npm',
      args: 'run react:dev:block3',
    },
    {
      name: 'frontend-svelte',
      cwd: '.',
      script: 'npm',
      args: 'run svelte:dev:block3',
    },
  ],
};
